name: deploy
run-name: Deploy to production

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: self-hosted
    steps:
      - name: Docker compose down
        run: docker compose down || true

      - name: Pull repository with submodules
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_ORG_TOKEN }}
          submodules: true

      - name: Echo Github Secrets
        run: echo '${{ secrets.ENV }}' > .env

      - name: Docker compose up
        run: docker compose up -d --build